name: CI

on:
  push:
    branches: 
     - 'main'
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout Tests
      uses: actions/checkout@v3
    - 
      name: Setup Node v16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    -
      name: Install dependencies
      run: npm ci
    -
      name: Setup Node v16
      run: npx eslint src

  tests_integrations:
    name: Tests integration Playwrigth
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout Tests
      uses: actions/checkout@v3
    -
      name: Setup Node v16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    -
      name: Install dependencies
      run: npm ci
    -
      name: Install Playwright Browsers
      run: npx playwright install --with-deps
    -
      name: Run Playwright tests with coverage
      env:
        CI: true
      run: npx nyc --reporter=json npx playwright test
    - 
      name: Upload coverage report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: coverage-report
        path: coverage/
        retention-days: 30
